business/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import IndexView, AboutView, RecruitingView, ContactView, QuoteoView,  ServiceView, ServiceDetail
# create_quote
app_name= 'business'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('service', ServiceView.as_view(), name='service'),
    path('about', AboutView.as_view(), name='about'),
    path('service_detail/<slug:slug>/', ServiceDetail.as_view(), name='service_detail'),

    path('recruiting', RecruitingView.as_view(), name='recruiting'),
    path('contact', ContactView.as_view(), name='contact'),
    path('create_quote', QuoteoView.as_view(), name='quote'),
    # path('create_quote', create_quote, name='create_quote'), 

   ]

config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from config import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _

urlpatterns = i18n_patterns(
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path ('', include('business.urls')), 
    path('traduction/', include('rosetta.urls')),


)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 
# if 'rosetta' in settings.INSTALLED_APPS:
#     urlpatterns += [
#         re_path(r'^rosetta/', include('rosetta.urls'))
#     ]

business/models.py
from django.db import models
from django.urls import reverse
from tinymce import models as tinymce_models
from django.core.exceptions import ValidationError
from django.utils.translation import gettext as _
# Create your models here.


CHOICES = (
    ('S1' ,'70 - 200'),
    ('S2' ,'201 - 400'),
    ('S3' ,'401 - 600'),
    ('S4' ,'601 - 1000'),
  
)



class Contact(models.Model):
    name    = models.CharField(max_length=150, verbose_name='Nom')
    email   = models.EmailField(verbose_name="E-mail" )
    phone   = models.CharField(verbose_name="Téléphone" , max_length=25)
    subject = models.CharField(max_length=150, verbose_name='sujet')
    message = models.TextField(null=True, blank=True)
    class Meta:
        verbose_name = _("contact")
        verbose_name_plural = _("contacts")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("business:contact", kwargs={"pk": self.pk})

 
   
class Hiring(models.Model):
    name        = models.CharField(max_length=150, verbose_name='Nom')
    email       = models.EmailField(verbose_name="E-mail", null=True, blank=True)
    phone       = models.CharField(verbose_name="Téléphone" , max_length=25)
    birth_date  = models.DateField() 
    birth_place = models.CharField(max_length=150, verbose_name='lieu de naissance', null=True, blank=True)
    message     = models.TextField(verbose_name='experience', null=True, blank=True)
    cv_file     = models.FileField(upload_to='media', verbose_name='CV', null=True, blank=True)

    class Meta:
        verbose_name = _("hiring")
        verbose_name_plural = _("hirings")
    
    def __str__(self):
        return str(self.email)
  

    def get_absolute_url(self):
        return reverse("business:hiring", kwargs={"pk": self.pk})




class Formule(models.Model):
    formule        = models.CharField(verbose_name="Pack nettoyage",max_length=150, )
    porte          = models.IntegerField(verbose_name="nombre de fenetre", null=True, blank=True)
    price          = models.IntegerField(verbose_name="prix", default=0)
    description     = models.TextField(verbose_name='Descriptions du pack', null=True, blank=True)
    class Meta:
        verbose_name = _("formule")
        verbose_name_plural = _("formules")

    def __str__(self):
        return self.formule

    def get_absolute_url(self):
        return reverse("business:quote", kwargs={"pk": self.pk})
 
    
class Bien(models.Model):
    name         = models.CharField(verbose_name="type de bien" , max_length=25)
    price        = models.IntegerField(verbose_name="prix", default=0)
    
    class Meta:
        verbose_name = _("bien")
        verbose_name_plural = _("biens")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("business:quote", kwargs={"pk": self.pk})  
    



class Surface(models.Model):
    surface                = models.CharField(choices=CHOICES,verbose_name="surface en m2", max_length=2)
    price                  = models.IntegerField(verbose_name="prix", default=0)
    class Meta:
        verbose_name = _("surface")
        verbose_name_plural = _("surfaces")

    def __str__(self):
        return self.surface

    def get_absolute_url(self):  
        return reverse("business:quote", kwargs={"pk": self.pk})  
    
    
class Quote(models.Model):
    email       = models.EmailField(verbose_name="E-mail")
    phone       = models.CharField(verbose_name="Téléphone" , max_length=25) 
    formule     = models.ForeignKey(Formule, blank=True, null=True, on_delete=models.CASCADE) 
    bien        = models.ForeignKey(Bien, blank=True, null=True, on_delete=models.CASCADE) 
    surface     = models.ForeignKey(Surface, blank=True, null=True, on_delete=models.CASCADE) 

    class Meta:
        verbose_name = _("quote")
        verbose_name_plural = _("quotes")

    def __str__(self):
        return self.email

    def get_absolute_url(self):
        return reverse("business:quote", kwargs={"pk": self.pk})
    
    def get_total_cost(self):
        return self.surface.price +  self.bien.price + self.formule.price


class Business(models.Model):
    name            = models.CharField(verbose_name="Nom de l'entreprise", max_length=100)
    logo            = models.ImageField(upload_to='images/logos', verbose_name='Logo')
    favicon         = models.ImageField(upload_to='images/logos', verbose_name="Favicon", blank=True, null=True)
    logo_negatif    = models.ImageField(upload_to='images/slides', verbose_name="Logo négatif", blank=True, null=True)
    title           = models.CharField(verbose_name="Titre", max_length=50, blank=True)
    adress          = models.CharField(verbose_name="Adresse", max_length=200, blank=True)
    email           = models.EmailField(verbose_name="email de l'entreprise", max_length=50, blank=True)
    email2          = models.EmailField(verbose_name="2eme email de l'entreprise", max_length=50, blank=True)
    email3          = models.EmailField(verbose_name="email de receptions, contact, devis, recrutement", max_length=50, blank=True)
    phone           = models.CharField(verbose_name="numéro de téléphone de l'entreprise", max_length=50, blank=True)
    phone2          = models.CharField(verbose_name="2eme numéro de téléphone de l'entreprise", max_length=50, null=True,blank=True)
    phone3          = models.CharField(verbose_name="3eme numéro de téléphone de l'entreprise", max_length=50, null=True,blank=True)
    about           = tinymce_models.HTMLField(verbose_name='Text a propos', blank=True, null=True)
    about_2          = tinymce_models.HTMLField(verbose_name="Page d'accueil", blank=True, null=True)
    about_photo2     = models.ImageField(verbose_name="Photo a propos Page d'accueil ", upload_to='images/slides', blank=True, null=True)
    mini_about      = models.TextField(verbose_name="Petit texte a propos de l'entreprise ( bas de page)", blank=True, null=True)
    about_photo     = models.ImageField(verbose_name="Photo a propos ", upload_to='images/slides', blank=True, null=True)
    facebook        = models.URLField(verbose_name="Lien page Facebook", max_length=300, blank=True, null=True)
    insta           = models.URLField(verbose_name="Lien page Instagram", max_length=300, blank=True, null=True)
    linkedin        = models.URLField(verbose_name="Lien page LinkedIn", max_length=300, blank=True, null=True)

    
    def __str__(self):
        return self.name
    def image_tag(self):
        return format_html('<img src="{}" height="150"  />'.format(self.logo.url))
    image_tag.allow_tags = True
    class Meta:
        verbose_name = ' Infomation'
        verbose_name_plural = ' Infomations'

    def clean(self):
        model = self.__class__
        if (model.objects.count() > 0 and
                self.id != model.objects.get().id):
            raise ValidationError("Vous ne pouvez pas rajouter d'entreprise")

    def get_recipient(self):
        return self.email3

class ActiveManager(models.Manager):
    def active(self):
        return self.filter(active=True)

class Slide(models.Model):
    photo      = models.ImageField(verbose_name="Slide haut de page", upload_to='slides/' )
    actif  = models.BooleanField(verbose_name='actif', default=True)
    objects = ActiveManager()

    class Meta:
        verbose_name = 'slide'
        verbose_name_plural = 'slides'
    
  
    def clean(self):
        model = self.__class__
        if (model.objects.count() > 0 and
                self.id != model.objects.get().id):
            raise ValidationError("Vous ne pouvez pas rajouter d'autres Slides")



class About(models.Model):
    name            = models.CharField(verbose_name="Nom de l'entreprise", max_length=100,  blank=True, null=True)
    image_high      = models.ImageField(upload_to='images/', verbose_name='image_1', blank=True, null=True)
    image_low       = models.ImageField(upload_to='images/', verbose_name="image_2", blank=True, null=True)
    title           = models.CharField(verbose_name="Titre", max_length=50, blank=True) 
    about_high      = tinymce_models.HTMLField(verbose_name='Text a propos', blank=True, null=True)
    about_low       = tinymce_models.HTMLField(verbose_name='Page a propos 2', blank=True, null=True)
 
    def __str__(self):
        return str(self.name)
    class Meta:
        verbose_name = 'about'
        verbose_name_plural = 'abouts'


class Service(models.Model):
    name            = models.CharField(verbose_name="service", max_length=100,  blank=True, null=True)
    slug = models.SlugField()
    image           = models.ImageField(upload_to='images/', verbose_name='image du service', blank=True, null=True)
    image_high      = models.ImageField(upload_to='images/', verbose_name='image_detail_1', blank=True, null=True)
    image_low       = models.ImageField(upload_to='images/', verbose_name="image_detail_2", blank=True, null=True)
    about_high      = tinymce_models.HTMLField(verbose_name='Text service', blank=True, null=True)
    about_low       = tinymce_models.HTMLField(verbose_name='Page service ', blank=True, null=True)
    
    def __str__(self):
        return str(self.name)
    class Meta:
        verbose_name = 'service'
        verbose_name_plural = 'services'

    def get_absolute_url(self):
        return reverse("business:service_detail", kwargs={"slug": self.slug})

business/views.py
from multiprocessing import context
from django.http import HttpResponse
from django.shortcuts import render
from django.core.mail import send_mail
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import TemplateView, ListView , DetailView
from django.views.generic.edit import CreateView
from .forms import ContactForm, QuoteForm, HiringForm
from .models import Bien, Contact, Formule, Quote, Hiring, Surface, Slide, About, Service
from django.utils.translation import gettext as _
# Create your views here.
from django.contrib import messages
from django.shortcuts import redirect
from config.settings import EMAIL_HOST_USER, EMAIL_RECIPIENT

###index 
from django.utils import translation
class IndexView(TemplateView):
    template_name= "index.html"
    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context["formules"] =Formule.objects.all()
        context["services"] =Service.objects.all()
        context["slide"] =Slide.objects.last()
        context["biens"] = Bien.objects.all()
        context["surfaces"] =Surface.objects.all()
        print('GET text', translation.get_language())
        return context


##ABOUT
class AboutView(TemplateView):
    template_name= "about.html"
    def get_context_data(self, **kwargs):
        context = super(AboutView, self).get_context_data(**kwargs)
        context["abouts"] =About.objects.all()
        return context

##services

class ServiceView(ListView):
    template_name= "services.html"
    model = Service
    context_object_name ="services"

class ServiceDetail(DetailView):
    model = Service
    template_name='services_detail.html' 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["services"] =Service.objects.all()
        return context


## CONTACT 

class ContactView(SuccessMessageMixin, CreateView):
    template_name= "contact.html"
    form_class= ContactForm
    model = Contact 
    success_message = "Votre message a été envoyé avec succès, Un agent vous contactera prochainement avec un appel téléphonique ou un e-mail."
    success_url = reverse_lazy('business:contact')
   
    def form_valid(self, form):
        try: 
            form.send_email() 
        except: 
            pass
        return super().form_valid(form)
    
      

## devis

class QuoteoView(SuccessMessageMixin, CreateView):
    template_name= "quote.html"
    form_class= QuoteForm
    model = Quote 
    success_message = "Un agent vous contactera prochainement avec un appel téléphonique ou un e-mail contenant les informations demandées."
    success_url = reverse_lazy('business:quote')
    def form_valid(self, form):
        try: 
            form.send_email() 
            print('form.send_email()' )
        except: 
            pass  
        return super().form_valid(form) 
    def get_context_data(self, **kwargs):
        context = super(QuoteoView, self).get_context_data(**kwargs)
        context["formules"] =Formule.objects.all()
        context["biens"] = Bien.objects.all()
        context["surfaces"] =Surface.objects.all()
        return context
   
#recrutements
class RecruitingView(SuccessMessageMixin, CreateView):
    template_name= "recrutement.html"
    form_class= HiringForm
    model = Hiring 
    success_message = "Votre demande a été soumise, Un agent vous contactera prochainement avec un appel téléphonique ou un e-mail." 
    success_url = reverse_lazy('business:recruiting')

    def form_valid(self, form):
        try: 
            form.send_email() 
        except: 
            pass
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request,form.errors)
        return redirect('business:recruiting') 

    

    
# def create_quote(request):
#     print('init create htmx or not ')
#     context = {}

#     form = QuoteForm()
#     # if request.POST:
#     #     if form.is_valid():
#     #         form.save(commit=False)
#     #         form.send_email() 
#     #         form.save()
#     #         print('is VAlid')
#     #         messages.success(request, f'Un agent vous contactera prochainement avec un appel téléphonique ou un e-mail contenant les informations demandées.')
#     #     else:
#     #         print('is NOT  VAlid', form.errors)
#     if request.htmx:
#         if form.is_valid():
#             form.save(commit=False)
#             # form.send_email() 
#             form.save()
#             return render(request, 'snippets/message.html', context)
#         # return HttpResponse(f'{quote.get_total_cost()}')
#     context["formules"] =Formule.objects.all()
#     context["biens"] = Bien.objects.all()
#     context["surfaces"] =Surface.objects.all()
#     context["form"] =form
#     context["message"] ='hello'

#     return render(request, 'quote.html', context)


# le service que vous avez demandé à un cout approximatif de  <strong>{total_cost}</strong> DA.    
# <div class="alert alert-primary" role="alert">
#   This is a primary alert—check it out!
# </div>

business/templates/quote.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
{% block title %}
<title>OCRAN NADAFA</title>
{% endblock %}
 <!--Page Title-->


<section class="page-title" style="background-image:url({% static 'images/background/bureau5.jpg' %})">
    <div class="auto-container">
        <h2>{% trans 'Obtenez un devis' %}</h2>
        <ul class="page-breadcrumb">
            <li><a href="{% url 'business:index' %}">{% trans 'Accueil' %}</a></li>
            <li>{% trans 'Obtenez un devis' %}</li>
        </ul>
    </div>
</section>
    <!--End Page Title-->

	<!-- Contact Form Section -->
	<section class="contact-form-section" style="background-image:url('images/background/contact.jpg' %})">
		<div class="auto-container">
			<!-- Sec Title -->
			<div class="sec-title">
				<h2>{% trans 'Obtenez un devis' %}</h2>
				<div class="text"> <p style="color:#242424;">{% trans 'Merci de remplir le formulaire pour avoir un devis approximatif.' %}</p></div>
			</div>
		
				
			<div class="ol-lg-6 col-md-6 col-sm-12">
				<!-- message -->
					 {% comment %} {% if messages %}
						{% for message in messages %}
							<div class="alert {{ message.tags }} alert-dismissible text-center" role="alert">
							<button type="button" class="close" data-dismiss="alert" aria-label="Close">
								<span aria-hidden="true">&times;</span>
							</button>
							{{response}}
							</div>
						{% endfor %}
					
					{% endif %}  {% endcomment %}
				   <!-- message -->

						
				<div id="messageQuote">
					{% include 'snippets/message.html' %}
					
				</div> 
			 </div>
			<div class="row clearfix">
				
				<!-- Form Column -->
				<div class="form-column col-lg-7 col-md-12 col-sm-12">
					<div class="inner-column">
						
						<!-- Contact Form -->
						<div class="contact-form">
								
							<!--Contact Form-->
						    {% comment %} <form hx-post="{% url 'business:create_quote' %}" hx-swap="innerHTML" hx-target="#messageQuote"> {% endcomment %}

							<form method="POST" action="{% url 'business:quote' %}">
								{% csrf_token %}  
								<div class="row clearfix">
									<div class="form-group col-lg-12 col-md-6 col-sm-12">
										<input type="email" name="email" id="id_email" value="" placeholder="{% trans 'E-Mail *' %}" required>
									</div>
									
									<div class="form-group col-lg-12 col-md-6 col-sm-12">
										<input type="text" name="phone" id="id_phone" value="" placeholder="{% trans 'Numéro +213 *' %}" pattern="^(?:0|\(?\+213\)?\s?|00213\s?)[1-79](?:[\.\-\s]?\d\d){4}$" required>
									</div>
									<div class="form-group col-lg-12 col-md-6 col-sm-12">
										<select class="custom-select-box" id="id_surface" name="surface">
											<option value=""> {% trans "Surface" %} </option>
											{% for  surface in surfaces %}
                                                <option value="{{surface.id}}">{{surface.get_surface_display}}</option> 
											{% endfor %}
										  </select>
									</div>
									<div class="form-group col-lg-6 col-md-12 col-sm-12">
										<select class="custom-select-box"  id="id_formule" name="formule">
											<option value="">{% trans "Sélectionner un pack" %}</option>
											{% for  formule in formules %}
                                                <option value="{{formule.id}}">{{formule.formule}}</option>
											{% endfor %}
										  </select>
									</div>
									<div class="form-group col-lg-6 col-md-12 col-sm-12" >
										<select class="custom-select-box" id="id_bien" name="bien">
											<option value=""> {% trans "Sélectionner le type de bien" %} </option>
											{% for  bien in biens %}
                                                <option value="{{bien.id}}">{{bien.name}}</option>
											{% endfor %}
										  </select>
									</div>
									 
									<input type="text" name="username" id="username" hidden="true" >

									<div class="form-group col-lg-12 col-md-12 col-sm-12">
										<button class="theme-btn btn-style-one" type="submit" ><span class="txt"  style="color:#fff;">{% trans 'Soumettre' %}</span></button>
									</div>
									
								</div>
							</form>
						</div>
					
					</div>
				</div>
				   
				<!-- Info Column -->
				<div class="info-column col-lg-5 col-md-12 col-sm-12">
					<div class="inner-column">
							<!-- Contact Info List -->
							{% for formule in formules %}	
						<ul class="contact-info-list"> 
							<li><strong>{{formule.formule}}</strong><br>{{formule.description}}</li>
						</ul>
							{% endfor %}
						
					</div>
				</div>
				
			</div>
			
		</div>
	</section>
	
	<!-- Contact Form Section -->

{% endblock content %}

business/templates/recrutement.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
{% block title %}
<title>OCRAN NADAFA</title>
{% endblock %}

  
    <!--Page Title-->
    <section class="page-title" style="background-image:url({% static 'images/background/bureau1.jpg' %})">
    	<div class="auto-container">
        	<h2> {% trans 'Recrutement' %} </h2>
            <ul class="page-breadcrumb">
            	<li><a href="{% url 'business:index' %}">{% trans 'Accueil' %}</a></li>
                <li>{% trans 'Recrutement' %}</li>
            </ul>
        </div>
    </section>
    <!--End Page Title-->  
	
    	<!-- Contact Form Section -->
	<section class="contact-form-section" style="background-image:url('images/background/contact.jpg' %})">
		<div class="auto-container">
			<!-- Sec Title -->
			{% include 'snippets/message.html' %}
			<div class="sec-title">
				<h2>{% trans 'Rejoignez notre équipe' %}</h2>
				<div class="text"> <p style="color:#242424;"> {% trans 'Merci de remplir formulaire ci-dessous,  nous vous contacterons dans les plus brefs délais.' %}  </p></div>
			</div>

			<div class="row clearfix">
				
				<!-- Form Column -->
				<div class="form-column col-lg-7 col-md-12 col-sm-12">
					<div class="inner-column">
						
						<!-- Contact Form -->
						<div class="contact-form">
								
							<!--Contact Form-->
							<form method="post" action="{% url 'business:recruiting' %}" enctype='multipart/form-data' >
								{% csrf_token %}
								<div class="row clearfix">
									<div class="form-group col-lg-6 col-md-6 col-sm-12">
										<input type="text" name="name" id="id_name" placeholder="{% trans 'Nom complet *' %}" required>
									</div>
									
									<div class="form-group col-lg-6 col-md-6 col-sm-12">
										<input type="tel" name="phone" id="id_phone"  placeholder="{% trans "Numéro *" %}" pattern="^(?:0|\(?\+213\)?\s?|00213\s?)[1-79](?:[\.\-\s]?\d\d){4}$" required>
									</div>
									<div class="form-group col-lg-6 col-md-6 col-sm-12">
										<input type="text" name="email" id="id_email"  placeholder="{% trans "E-mail" %}" >
									</div>
									<div class="form-group col-lg-6 col-md-6 col-sm-12">
										<input type="date" name="birth_date" id="id_birth_date"   placeholder="{% trans "Date de naissance *" %}" required>
									</div>
                                    {% comment %} <div class="form-group col-lg-6 col-md-6 col-sm-12">
										<input type="text" name="birth_place" id="id_birth_place"  placeholder="{% trans "Lieu de naissance *" %}" required>
									</div> {% endcomment %}
									<div class="form-group col-lg-12 col-md-12 col-sm-12">
										<textarea name="message" id="id_message"  placeholder="{% trans "Experience" %}"></textarea>
									</div>
                                    <div class="form-group col-lg-12 col-md-12 col-sm-12">
                                        <input type="file" name="cv_file" id="id_cv_file"  placeholder="{% trans "télécharger votre cv *" %}">
									</div>
									<input type="text" name="username" id="username" hidden="true" >
									
									<div class="form-group col-lg-12 col-md-12 col-sm-12">
										<button class="theme-btn btn-style-one" type="submit" ><span class="txt"  style="color:#fff;">{% trans 'Soumettre' %}</span></button>
									</div>
									
								</div>
							</form>
						</div>
					
					</div>
				</div>
				   
				<!-- Info Column -->
				<div class="info-column col-lg-5 col-md-12 col-sm-12">
					<div class="inner-column">
						
						<!-- Contact Info List -->
						<ul class="contact-info-list">
							<li><strong>{% trans 'Adresse :' %}</strong><br>{{business.adress}}</li>
							{% comment %} <li><strong>{% trans 'Adresse :' %}</strong><br>{% trans 'Centre commercial et d&#8216;affaire Mohammadia mall 16058 Alger, Algérie' %}</li> {% endcomment %}
						</ul>
						<!-- Contact Info List -->
						<ul class="contact-info-list">
							<li><strong>{% trans 'Numéro : ' %}</strong><a href="tel:698092844" dir="ltr">{% trans '0698 09 28 44 ' %}</a></li>
							<li><strong>{% trans 'Fix : ' %}</strong><a href="tel:23804261" dir="ltr">{% trans '023 80 42 61' %}</a></li>
							<li><strong>{% trans "E-mail  : " %}</strong><a href="mailto:contact@ocrannadafa.com" >{% trans 'contact@ocrannadafa.com' %} </a></li>
						</ul>
						<!-- Contact Info List -->
						<ul class="contact-info-list">
							<li><strong>{% trans "Horaires d'ouverture :" %} </strong><br> {% trans '08:00 AM - 16:30 PM' %} <br> {% trans 'DIMANCHE  – JEUDI' %}</li>
						</ul>
						
					</div>
				</div>
				
			</div>
			
		</div>
	</section>
	{% include 'snippets/devis_cta.html' %}

{% endblock content %}

business/templates/services.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
{% block title %}
<title>OCRAN NADAFA</title>
{% endblock %}
    <!--Page Title-->
    <section class="page-title" style="background-image:url({% static 'images/background/contact.jpg' %})">
    	<div class="auto-container">
        	<h2>{% trans 'Services' %}</h2>
            <ul class="page-breadcrumb">
            	<li><a href="{% url 'business:index' %}">{% trans 'Accueil' %}</a></li>
                <li>{% trans 'Services' %}</li>
            </ul>
        </div>
    </section>
    <!--End Page Title-->
		<!--Sidebar Page Container-->
     <!-- Services Section Three -->
	<section class="services-section-three" >
		<div class="auto-container">
			
			<!-- Sec Title -->
			<div class="sec-title centered">
				<h3>{% trans 'OCRAN NADAFA Toujours étincelants !' %}</h3>
				<div class="text">{% trans 'En faisant appel à' %} <strong>{% trans 'OCRAN NADAFA' %}</strong>{% trans ', vous avez le confort d’une prestation bien faite, réalisée par une equipe qualifié.' %}</div>
			</div>
			
			<div class="row clearfix">
				{% for service in services %}
				
					<!-- Service Block -->
						<div class="service-block-three style-two col-lg-3 col-md-6 col-sm-12">
							<div class="inner-box wow fadeInUp" data-wow-delay="0ms" data-wow-duration="1500ms">
									<div class="image">
									<a href="{{service.get_absolute_url}}">
										<img src="{{service.image.url}}" style="width:278px; height:185px;" alt="" /></a>
									</div>
									<div class="lower-content">
											<a href="{{service.get_absolute_url}}"><h3  style="color:black;">{{service.name}}</h3></a>
										<div class="text"> </div> <br>
									<a href="{{service.get_absolute_url}}">
										<p class="read-more">{% trans 'En savoir plus' %}</p>	</a>
									</div>
							</div>
						</div>
				
				{% endfor %}
		
          	</div>
          
        </div>
	
	</section>
	<!-- End Services Section -->
        

    </div>  
	{% include 'snippets/devis_cta.html' %}

{% endblock content %}