business/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import IndexView, AboutView, RecruitingView, ContactView, QuoteoView,  ServiceView, ServiceDetail
# create_quote
app_name= 'business'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('service', ServiceView.as_view(), name='service'),
    path('about', AboutView.as_view(), name='about'),
    path('service_detail/<slug:slug>/', ServiceDetail.as_view(), name='service_detail'),

    path('recruiting', RecruitingView.as_view(), name='recruiting'),
    path('contact', ContactView.as_view(), name='contact'),
    path('create_quote', QuoteoView.as_view(), name='quote'),
    # path('create_quote', create_quote, name='create_quote'), 

   ]

config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from config import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _

urlpatterns = i18n_patterns(
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path ('', include('business.urls')), 
    path('traduction/', include('rosetta.urls')),


)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 
# if 'rosetta' in settings.INSTALLED_APPS:
#     urlpatterns += [
#         re_path(r'^rosetta/', include('rosetta.urls'))
#     ]

templates/base.html
{% load static %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}
{% get_language_info for LANGUAGE_CODE as lang %}
{% get_language_info_list for LANGUAGES as languages %}
<!DOCTYPE html>
<html lang="{{LANGUAGES}}" dir="{% if LANGUAGE_CODE == 'ar' %}rtl{% else %}ltr{% endif %}">
{% block title %}
  <title>{{business.title}}</title>
{% endblock %}
<head>
<meta charset="utf-8">
<!-- Stylesheets -->
<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'css/style.css' %}" rel="stylesheet">
<link href="{% static 'css/responsive.css' %}" rel="stylesheet">

<link rel="{% static 'shortcut icon" href="images/favicon.png' %}" type="image/x-icon">
<link rel="icon" href="{% static 'images/favicon.png' %}" type="image/x-icon">

<!-- Responsive -->
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">

<meta name="language" content="{{LANGUAGES}}" />
</head>
{% include 'navbar.html' %}
 {% if LANGUAGE_CODE == 'ar' %}
    <style>
      h1, h2,  h4, h5, h6, a, p,ul, ul, li, span, .text h4, a, .span a, text, span, div.bold-text, .footer-widget div.widget-content {
        text-align: right;
        font-weight: bold;
      
      }
    .counter-title {
      text-align: center;
    }
     .header-right {
          margin-right: auto;
      }
      .megamenu {
            left: 0; 
            right: 100%;
      }
     
      main-footer .footer-widget h2:after {
          {% comment %} position: absolute; {% endcomment %}
          content: '';
          left: 0px;
          bottom: 0px;
          width: 30px;
          height: 1px;
          background-color: #242424;
      }


    </style>
  {% endif %} 

<body >

    {%block scripts%}
    {%endblock scripts%}
    {% block content %}
    
    {% endblock content %}
  
<!--Scroll to top-->
<div class="scroll-to-top scroll-to-target" data-target="html"><span class="fa fa-angle-up"></span></div>
    {% include 'footer.html' %}

<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/jquery-ui.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.fancybox.js' %}"></script>
<script src="{% static 'js/isotope.js' %}"></script>
<script src="{% static 'js/owl.js' %}"></script>
<script src="{% static 'js/wow.js' %}"></script>
<script src="{% static 'js/isotope.js' %}"></script>
<script src="{% static 'js/appear.js' %}"></script>
<script src="{% static 'js/scrollbar.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>
<script src="https://kit.fontawesome.com/d08376f6a2.js" crossorigin="anonymous"></script>
<script src="https://unpkg.com/htmx.org@1.5.0" ></script>
<!-- <script type="text/javascript" src="{% static "js/site-base.js" %}"></script> -->
<!-- <script type="text/javascript" src="{% static "CACHE/js/awesome.8dd1a2872443.js" %}" charset="utf-8"></script> -->
<script>
    document.body.addEventListener('htmx:configRequest', (event) => {
        event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
    })
</script>
</body>


</html>

templates/footer.html
{% load static %}
{% load i18n %}

	<!--Main Footer-->
  <footer class="main-footer">
		<div class="auto-container">
        	<!--Widgets Section-->
            <div class="widgets-section">
            	<div class="row clearfix">
                	
                    <!--big column-->
                    <div class="big-column col-lg-6 col-md-12 col-sm-12">
                        <div class="row clearfix">
                        
                            <!--Footer Column-->
                            <div class="footer-column col-lg-7 col-md-6 col-sm-12">
                                <div class="footer-widget logo-widget">
									<div class="logo">
                                    	<a href=""><img src="{{business.logo_negatif.url}}" alt="" /></a>
                                    </div>
                                    <div class="text" style="text-align: center"><strong>{{business.title}}</strong></div>
										
									</div>
							</div>
							
							<!--Footer Column-->
                            <div class="footer-column col-lg-5 col-md-6 col-sm-12">
                                <div class="footer-widget links-widget">
                                	<h2>{% trans "Liens utiles" %} </h2>
									<div class="widget-content">
										<ul class="list">
                                        	<li><a href="{% url 'business:about' %}">{% trans "PRÉSENTATION" %}</a></li>
                                            <li><a href="{% url 'business:service' %}">{% trans "SERVICES" %}</a></li>
                                            <li><a href="{% url 'business:quote' %}">{% trans "DEVIS" %}</a></li>
                                            <li><a href="{% url 'business:recruiting' %}">{% trans "RECRUTEMENT" %}</a></li>
                                            <li><a href="{% url 'business:contact' %}">{% trans "CONTACT" %}</a></li>
                                        </ul>
                                    </div>
								</div>
							</div>
						
						</div>
					</div>
					
					<!--big column-->
                    <div class="big-column col-lg-6 col-md-12 col-sm-12">
                        <div class="row clearfix">
                        <!--Footer Column-->
						<div class="footer-column col-lg-5 col-md-6 col-sm-12">
							<div class="footer-widget contact-widget">
								<h2>{% trans "Contact" %} </h2>
								<div class="widget-content">
									<span class="fa fa-phone"> <a dir="ltr" href="tel:23804261" class="contact-number">{{business.phone}}</span></a>
									<span class="fa fa-phone"> <a dir="ltr" href="tel:698092844" class="contact-number">{{business.phone2}}</span></a>
									
									<ul>
										<li ><i class="fa fa-map-marker" aria-hidden="true"></i> {{business.adress}} </li>
										<li > <i class="fa fa-envelope" aria-hidden="true"></i><a href="mailto:{{business.email}}" > {{business.email}} </li>
									</ul>
								</div>
							</div>
						</div>
						
                            <!--Footer Column-->
                            <div class="footer-column col-lg-5 col-md-6 col-sm-12">
                                <div class="footer-widget contact-widget">
									<h2>{% trans "réseau sociaux " %}</h2>
									
										<ul class="social-icons">
											<li><a href="https://wa.me/213698092844"><span class="fab fa-whatsapp">  {{business.phone2}}</span></a></li>
											<li><a href="https://viber.me/213698092844"><span class="fab fa-viber">  {{business.phone2}} </span></a></li>
											<li><a href="{{business.facebook}}"><span class="fab fa-facebook-f"> OCRAN-Nadafa </span></a></li>
											<li><a href="{{business.insta}}"><span class="fab fa-instagram"> ocran_nadafa </span></a></li>
										
										</ul>
								
								</div>
							</div>
							
							
						
						</div>
					</div>
					
				</div>
			</div>
			
			<!--Footer Bottom-->
            <div class="footer-bottom clearfix">
                <div class="pull-center">
                    <div class="copyright"><a href="https://www.octopus-consulting.com/" target="_blank"> Octopus-consulting</a></div>
                </div>
                
            </div>
			
		</div>
	</footer>

</body>

templates/navbar.html
{% load static %}
{% load i18n %}
		<!-- Header Style Three -->
    <header class="main-header header-style-three">
      <!--Header Top-->
      <div class="header-top">
          <div class="auto-container clearfix">
              <div class="top-left clearfix">
                  <div class="text" dir="ltr"> <span class="icon flaticon-call-answer"></span>{% trans " Appelez-nous:" %} <a href="tel:698092844" dir="ltr" class="number"> {{business.phone2}} </a></div>
        
              </div>
              <div class="top-right clearfix">
                  <!-- Info List -->
                    <ul class="info-list">
                        {% comment %} <li class="quote"><a href="{% url 'business:create_quote' %}">{% trans "Obtenez un devis gratuit" %}</a></li>  {% endcomment %}
                       
                    </ul>

              </div>
              
          </div>
      </div>
      <!-- End Header Top -->

      <!-- Header Upper -->
      <div class="header-upper">
          <div class="inner-container">
              <div class="auto-container clearfix">
                  <!--Info-->
                  <div class="logo-outer">
                      <div class="logo"><a href="{% url 'business:index' %}"><img src="{% static 'images/logo.png' %}"  alt="" title="" ></a></div>
                  </div>

                  <!--Nav Box-->
                  <div class="nav-outer clearfix">
                      <!--Mobile Navigation Toggler For Mobile--><div class="mobile-nav-toggler"><span class="icon flaticon-menu-1"></span></div>
                      <nav class="main-menu navbar-expand-md navbar-light">
                          <div class="navbar-header">
                              <!-- Togg le Button -->      
                              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                                  <span class="icon flaticon-menu-1"></span>
                              </button>
                          </div>
                          
                          <div class="collapse navbar-collapse clearfix" id="navbarSupportedContent">
                              <ul class="navigation clearfix" >
                              {% if LANGUAGE_CODE == 'fr' %}
                                    <li ><a href="{% url 'business:index' %}"  >{% trans "ACCUEIL" %}</a> </li>
                                    <li ><a href="{% url 'business:about' %}" >{% trans "PRÉSENTATION" %}</a> </li>
                                    <li > <a href="{% url 'business:service' %}" >{% trans "SERVICES" %}</a> </li>
                                    <li ><a href="{% url 'business:quote' %}" >{% trans "DEVIS" %}</a> </li>
                                    <li ><a href="{% url 'business:recruiting' %}" >{% trans "RECRUTEMENT" %}</a> </li>
                                    <li ><a href="{% url 'business:contact' %}" >{% trans "CONTACT" %}</a></li> 
                               {% else %}
                                    <li ><a href="{% url 'business:contact' %}" >{% trans "CONTACT" %}</a></li> 
                                    <li ><a href="{% url 'business:recruiting' %}" >{% trans "RECRUTEMENT" %}</a> </li>
                                    <li ><a href="{% url 'business:quote' %}" >{% trans "DEVIS" %}</a> </li>
                                    <li > <a href="{% url 'business:service' %}" >{% trans "SERVICES" %}</a> </li>
                                    <li ><a href="{% url 'business:about' %}" >{% trans "PRÉSENTATION" %}</a> </li>
                                    <li ><a href="{% url 'business:index' %}" >{% trans "ACCUEIL" %}</a> </li>
                                {% endif %} 
                                <li>
                                    {% if LANGUAGE_CODE == 'ar' %}
                                        <a href="/fr/"> 
                                            <img src="{% static 'images/fr.png' %}"  alt="FR" title="FR" style="height:25px; width:35px;">
                                        </a>
                                    {% else %}
                                        <a href="/ar"> 
                                            <img src="{% static 'images/dz.png' %}"  alt="AR" title="AR" style="height:25px; width:35px;">
                                        </a>
                                    {% endif %} 
                                </li>

                                        {% comment %} <ul>
                                            <li {% if LANGUAGE_CODE == 'fr' %} class="active"{% endif %}><a href="/fr"> <img src="{% static 'images/fr.png' %}"  alt="FR" title="FR" style="height:25px; width:35px;"></a></li>
                                            <li {% if LANGUAGE_CODE == 'ar' %} class="active "{% endif %}><a href="/ar"><img src="{% static 'images/dz.png' %}"  alt="AR" title="AR" style="height:25px; width:35px;"></a></li>
                                            {% if config.ln_dz %}
                                            <li {% if LANGUAGE_CODE == 'ar' %} class="active "{% endif %}><a href="/ar"><img src="{% static 'images/dz.png' %}"  alt="AR" title="AR" style="height:25px; width:35px;"></a></li>
                                            {% endif %}
                                            
                                        </ul>
                                  </li> {% endcomment %}
                              </ul>
                          </div>
                          
                      </nav>
                      <!-- Main Menu End-->
                      
                  </div>
              </div>
          </div>
      </div>
      <!--End Header Upper-->

    <!-- Mobile Menu  -->
      <div class="mobile-menu">
          <div class="menu-backdrop"></div>
          <div class="close-btn"><span class="icon flaticon-cancel"></span></div>
          
          <nav class="menu-box">
              <div class="nav-logo"><a href="{% url 'business:index' %}"><img src="{% static 'images/logo.png' %}"  alt="" title=""></a></div>
              <ul class="navigation clearfix"><!--Keep This Empty / Menu will come through Javascript--></ul>
      <!--Social Links-->
      
  </header>
  <!-- End Main Header -->
</body>